apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ .Values.label }}-{{ .Values.env }}"
spec:
  type: ClusterIP
  ports:
    - name: "https"
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: "zmq"
      port: 3030
      targetPort: 3030
      protocol: TCP
  selector:
    app: {{ .Values.label }}