import * as fs from 'fs'
const numTokens: number = 41
const descriptions: string[] = [
  'Dave Vanilla is a psycho. Pretty much everything that comes out of his mouth makes zero sense. He doesn’t buy anything inside Dusko either. He comes in, says nonsense, leaves.',
  'Ms. Lizette is a lot to handle. She generally shows up around 3 AM to fill up her gas tank, but it seems like it’s just an excuse to flirt with Vincent.',
  'Helga Quantum is a bold and rich customer that’s not afraid to argue with the Dusko crew.',
  'Kat is a handywoman with a utility belt. She stops by Dusko to and from her fix-it jobs.',
  'Magic Mel claims to be a magician. No one asks to hear about his tricks, but that’s okay because he’ll just ramble without being provoked.',
  'Weatherman is part of the Neutral News Network, which is owned by Parafaze Corp. Every forecast is either “room temp” or “luke-warm”.',
  'Suave Juan is a tv personality from a late night infomercial. He provides a phone service to talk you back to sleep with his smooth seductive accent.',
  'Anchorwoman is part of the Neutral News Network, which is owned by Parafaze Corp. Suspiciously her reports never cover the nefarious acts of Parafaze Corp…',
  'Harold is just a businessman who tends to overindulge in Dusko’s signature snack the “cactus cream filled donut”.',
  'Hariette is less than pleased to set foot inside the greasy gas station and tries to make it the quickest stop possible.',
  'Hector is a robot that is supposedly programmed to be a gas attendant, his efficiency remains to be seen.',
  'Carlo lets his brother do all the talking, so he can catch up on his sleep. He has a zen-like quality and doesn’t let customers bring him down. His dark sunglasses add to his mystique and no one can tell if he’s sleeping or silently judging.',
  'Spokesmodel is seen on billboards all over town selling cigarettes with catchy slogans such as “I’m sending you a smoke signal, baby.”',
  'Trucker is another cog in the corporate machine. He eats his food while on the job, which may or may not be the reason he’s always carsick.',
  'Deliveryman is unaware of what exactly is in the boxes he’s delivering from Parafaze to Dusko. Odds are the contents aren’t pleasant…',
  'Sabrina is drifter and traveled the desert by motorcycle, that is until it broke down outside of dusko, now she’s their newest hire! She may be reluctant to join the Dusko crew, but she’s without a doubt the strongest and smartest member of the team.',
  'Moon doesn’t mess around. She knows her order and wants to get out the gas station as soon as possible.',
  'Vincent is serving up snacks, gas and sass. He is equal parts hardworking and fast talking. While he may appear ultra-efficient, he’s really just in a hurry to get back to finish the job and get back to watching tv.',
  'Dino is the leader of the junior executives. She wants to please her bosses by any means necessary, even if it means she’ll make a few enemies at the gas station.',
  'Whittaker is part of the Neutral News Network, which is owned by Parafaze Corp. He has a “talk show” that feels a bit more like a propaganda machine…',
  'The Chauffeur is Kilroy’s personal driver. When he’s not driving Kilroy around, he can be found loitering in the breakroom eating donuts or sitting quietly in the company car.',
  'Jordash is a simple farmer, a relatively gentle customer not looking for any trouble.',
  'The Man from Elsewhere is the CEO running Parafaze. He’s seldom seen in public, and rarely ever speaks. It’s best not to look into his red eyes.',
  'Chic is a junior executive. She appears to be the sweetest of all the Parafaze Corp. but that’s probably just an act…',
  'Tony Ranger appears to be half asleep all of the time. The Dusko crew always offers him coffee but he ignores them and buys alcohol instead.',
  'Otto Mattic always seems to be a little out of it. He sort of mumbles his order and stumbles on his way out the door.',
  'The Host is the host of an old sci-fi tv show called “The Lower Level Zone.” He’s got a relaxed demeanor and is playing it cool but everything coming out of his mouth is mostly cryptic.',
  'Valet works in the underground parking garage at Parafaze Corp. Rumor has it that the air quality isn’t that great down there, so he’s forced to wear what appears to be a hazmat suit.',
  'Sleepwalker is a character from an episode of an old sci-fi tv show called “The Lower Level Zone.” The show is cryptic and hard to follow at times, but that’s okay because Sleepwalker doesn’t really know what’s going on either.',
  'Wutzhizneim is a character from a comic book that’s sold inside of Dusko. He doesn’t appear to be a hero, villain, or anti-hero. The general plot seems to revolve around him doing whatever the hell he wants.',
  'High School Joe is just a weird kid that loiters around Dusko, and claims to be doing his math homework while hogging up the tables and chairs.',
  'Cover Girl is often seen on the cover of Swank Magazine. She’s often associated with luxury products for the rich and elite.',
  'Mississippi is a robot side-kick from the dusty arcade game called “Retrogrademan”. Either the game itself is glitchy or Mississippi always seems to be on the fritz.',
  'Terry Quantum is an eccentric customer. He’s got money, style, a wife, and a vague accent.',
  'Kilroy is a flamboyantly dressed cowboy. He’s the second in command at Parafaze Corp. and he’s not afraid to show people he’s the one calling the shots. If he doesn’t have a cigarette in his mouth, he probably has expletives coming out of his mouth.',
  'Anchorman is part of the Neutral News Network, which is owned by Parafaze Corp. He doesn’t really know what’s going on, he’s just reading the teleprompter.',
  'Harley is a junior executive. Her sunglasses are a conversation piece and do most of the talking for her. Needless to say - don’t get in her way.',
  'Mr. Myth is a psychic. He drives around in a purple van and frequently stops by Dusko. He claims to know a lot, but never knows what to order.',
  'Retrogrademan is the hero of the dusty arcade game called “Retrogrademan”. He speaks like a 70’s radio DJ, only instead of band names and song titles, it’s about time travel and outer space.',
  'Conrad is a wildcard. In a way he’s a vigilante and germaphobe wrapped up into one. He travels all over the desert and destroys every bit of dirt that gets in his way.',
  'JR is the youngest employee of the gas station. He’s also an amnesiac, so Dusko is all he knows. JR won’t be making employee of the month anytime soon, because he’s too busy playing video games.',
]
const categories: string[] = [
  'Regulars',
  'Regulars',
  'Regulars',
  'Regulars',
  'Regulars',
  'Parafaze Corp.',
  'As Seen on TV',
  'Parafaze Corp.',
  'Regulars',
  'Regulars',
  'Dusko Crew',
  'Dusko Bros',
  'As Seen on TV',
  'Parafaze Corp.',
  'Parafaze Corp.',
  'Dusko Crew',
  'Regulars',
  'Dusko Bros',
  'Parafaze Corp.',
  'Parafaze Corp.',
  'Parafaze Corp.',
  'Regulars',
  'Parafaze Execs',
  'Parafaze Corp.',
  'Regulars',
  'Regulars',
  'As Seen on TV',
  'Parafaze Corp.',
  'As Seen on TV',
  'As Seen on TV',
  'Regulars',
  'As Seen on TV',
  'As Seen on TV',
  'Regulars',
  'Parafaze Execs',
  'Parafaze Corp.',
  'Parafaze Corp.',
  'Regulars',
  'As Seen on TV',
  'Regulars',
  'Dusko Crew',
]

for (let i = 0; i < numTokens; ++i) {
  const metadata = {
    name: 'DUSKO',
    description: descriptions[i],
    image: `ipfs://QmW3wpFEqaiqfGJz5wWeiFW3wDMNe7RXya1ks6DHQeiurj/dusko_assets/${
      i + 1
    }.jpg`,
    attributes: [
      { trait_type: 'Category', value: categories[i] },
    ],
  }
  fs.writeFileSync(`dusko_metadata/${i + 1}`, JSON.stringify(metadata))
}
